train_dataset: mini-imagenet
train_dataset_args: {split: train, augment: cropaug}
val_dataset: mini-imagenet
val_dataset_args: {split: train_phase_val}
fs_dataset: mini-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: lvvit_micro_80
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 64}

batch_size: 512
max_epoch: 300
optimizer: adamw
optimizer_args: {lr: 5.e-4, weight_decay: 0.05,
                 eps: 1.e-8,
                 sched: cosine,
                 warmup: 5, 
                 warmup_lr: 1.e-6, 
}

save_epoch: 5
visualize_datasets: true
