dataset: mini-imagenet
#dataset: tiered-imagenet
dataset_args: {split: test}
model: meta-baseline
model_args:
    encoder: nest_micro_80
    encoder_args: {}
#./save/MODEL_FOLDER/EPOCH_X.pth

# Replace load with load_encoder for loading the encoder only (e.g. for testing Classifier-Baseline)
